### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by jt3k** [chrisveness/crypto#4]
Hi! Could you publish your package to npm ?

Thank you for your work.

**Comment by chrisveness** [comment]
As mentioned in the readme, these routines are not really intended for production use (though I do know of cases where they are being used in production), so I don't really feel included to encourage their use by publishing on npm.

If you wish to use them, you can take local copies, but for production use I would recommend the Web Cryptography API or possibly Node's crypto library, as mentioned in the readme.
