### ISSUE TITLE
npm?

### ISSUE THREAD

**Issue by adamjimenez** [chrisveness/crypto#5]
Any reason why this isn't on npm?
I tried to do: `yarn add crypto-libraries`

**Comment by chrisveness** [comment]
These libraries are reference implementations closely tracking the standards, intended for people interested in studying the algorithms. Not only are they not optimised for performance, but cryptography is a dark art, and I don't feel qualified to make assurances about security.

As mentioned in the readme,  for production use I would recommend the Web Cryptography API for the browser, or the crypto library in Node.js. PHP also has native libraries.

**Comment by adamjimenez** [comment]
Thanks for pointing to me towards Web Crypto API
